<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>CB - Jorge Ramirez</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body id="body">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">CB - JramirezGranada</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h3 class="my-4">Add new Interval</h3>
            <form id="interval-form">
                <div class="form-group">
                    <input type="date" class="form-control" placeholder="Start Date (2018-08-01)" name="start_date"
                           id="start_date">
                    <br>
                    <input type="date" class="form-control" placeholder="End Date (2018-08-01)" name="end_date"
                           id="end_date">
                    <br>
                    <input type="text" class="form-control" placeholder="Price" name="price" id="price">
                    <br>
                    <a href="#" id="add-interval" class="btn btn-success">Add Interval</a>
                </div>
            </form>

            <br><br>
            <h5 class="my-m4">Truncate Intervals Table</h5>
            <a href="#" id="truncate-interval" class="btn btn-danger">Truncate Table</a>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <h3 class="my-4">Intervals</h3>
            <div class="alert alert-danger errors" style="display: none"></div>
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Price</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody id="interval-list-table">

                </tbody>
            </table>

        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<script src="/resources/js/intervals.js"></script>

</body>
</html>